/**
This file was generated by build tool. Don't change it!
*/
//#include "{{ct.header}}"
//#include "core/files_io.h"
#include "Serialize.h"

{% for cl_include in includes %}
#include "{{cl_include.header}}"
{% endfor %}
using namespace oxygine;
using namespace pugi;

REGISTER_ACTOR({{ct.className}});

